# Generated by Django 4.2.7 on 2023-11-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('duration', models.IntegerField(blank=True)),
                ('rating', models.FloatField(blank=True)),
            ],
        ),
    ]
